### ISSUE TITLE
Creación controlador expediente

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#12]

**Comment by HaritzPuerto** [comment]
@fraanii94 no tenía controladores asignados

**Comment by steveomatic** [comment]
Ey @HaritzPuerto  y @fraanii94 , a alguno le importa si hago yo el controlador para la vista buscador_expedientes? (es esta, no?)

**Comment by steveomatic** [comment]
He creado la vista y el controlador. Necesito que lo miréis y me digáis qué falta
El ejemplo está en el informe:
https://docs.google.com/document/d/1-46kF4qolLMxpUbUNbaQuyl9siVkgLdyOig_NEVUjLg/edit
