### ISSUE TITLE
DEADLINE: 3 DE MAYO

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#19]
@soutoner @steveomatic @FelipeSulser @AlvaroFaure @fraanii94

**Comment by HaritzPuerto** [comment]
Para el 3 de mayo debe estar el proyecto listo para entregar, no los issue hechos porque luego hay que mergearlos y eso lleva tiempo.

**Comment by steveomatic** [comment]
3 de Mayo es mañana. Acelerad.
@HaritzPuerto 
@FelipeSulser 
@AlvaroFaure 
@fraanii94 
@soutoner

**Comment by HaritzPuerto** [comment]
El proyecto debe estar listo ya!! estamos en la fase de mergeo de todas nuestras ramas, pero aún queda la de @fraanii94 debido a que el profe aún no le ha contestado algo. Deberías haber ido al lab y haberle preguntado allí. Mañana quiero que esté listo. A partir del lunes hacemos la documentación!!
@steveomatic @FelipeSulser @fraanii94 @AlvaroFaure @soutoner

**Comment by HaritzPuerto** [comment]
Importante! Quiero a todo el mundo revisando la master!!!
@soutoner @fraanii94 @AlvaroFaure @steveomatic @FelipeSulser Si hay que cambiar algo, hoy es el momento de indicarlo!!!!!!!!!!!
I want everybody revising master branch!
Je veux tout le monde travaille!
일하세요~ 칠문이 있으면 물어 보세요~~

**Comment by steveomatic** [comment]
Done!
Listo!
Fertig!
сделать

**Comment by AlvaroFaure** [comment]
11000010 10100001 01000111 01100101 01101110 01101001 01100001 01101100 00100001

**Comment by HaritzPuerto** [comment]
끝내다~
