### ISSUE TITLE
DEADLINE PR: 30 abril

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#20]
El 30 de abril quiero todos los issue con un PR asociado.
@soutoner @steveomatic @FelipeSulser @AlvaroFaure @fraanii94 

El 1 comenzaremos a mergear como muy tarde.

**Comment by HaritzPuerto** [comment]
Mi consejo es que el martes terminéis una tarea y el resto del tiempo la otra. Empezad primero con las vistas!!!

**Comment by steveomatic** [comment]
Ya incluso ha pasado la fecha y faltan cosas

**Comment by HaritzPuerto** [comment]
Falta solo lo de @fraanii94

**Comment by steveomatic** [comment]
ya hice la de fran, cierro
