### ISSUE TITLE
DAO

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#21]
¿DAO es el backing bean? ¿Es lo que representa la capa de negocio? Si es así, más adelante aprenderemos a usar los Enterprise beans (no sé si es lo mismo)

**Comment by FelipeSulser** [comment]
No.
Pero si vamos a usar en algún sitio datos de las entidades JPA no las uses directamente.
Crea una clase java llamada DaoNombreEntidad donde se manejen los datos de la entidad.

Es simplemente un patrón software, nada nuevo.

**Comment by steveomatic** [comment]
A ver, yo lo estoy haciendo así:

Está la vista, que se comunica con el controlador. Ahora bien, el controlador no tiene NINGÚN dato de la base de datos, sólo tiene métodos que se comunican con la vista y otros métodos que se comunican con el DAO. El DAO le devuelve los datos al controlador, y éste a la vista para display.

**Comment by FelipeSulser** [comment]
Yes my friend

**Comment by steveomatic** [comment]
Esto está resuelto.
