### ISSUE TITLE
web.xml configuration file

### ISSUE THREAD

**Issue by steveomatic** [HaritzPuerto/SSCEntrega2#25]
PLEASE PAY EXTREME AMOUNTS OF ATTENTION:

In order to get the .jsf files rendered and shown as an html when deploying the server, I had to change and configure file web.xml, namely adding the following to the <servlet-mapping> section:

http://pastebin.com/cpyBiQeH

And now I can render and see visuals. Did this already work for you? 
I will mark this issue as IMPORTANT.

**Comment by FelipeSulser** [comment]
O TAMBIEN PUEDES hacer localhost:8080/faces/.... en tu navegador

**Comment by HaritzPuerto** [comment]
Lo de felipe me funciona a mi. A no me gusta tocar los archivos de configuración... xDDD

**Comment by steveomatic** [comment]
Ok, pues entonces lo dejamos así, a mí también me va como decís. Voy a cancelar la pr.
