### ISSUE TITLE
imports controlador (para Scoped y ManagedBean)

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#32]
Usad 
import javax.inject.Named;
import javax.enterprise.context.RequestScoped; //o el que os corresponda

si no, tendréis problemas. Además, el profesor usa este.
Tendréis que añadir la biblioteca de Java EE 7 API como hicimos en clase.
@steveomatic cámbialo en tu controlador.
@FelipeSulser @fraanii94 @AlvaroFaure @soutoner

**Comment by steveomatic** [comment]
¿Puedes poner aquí claramente qué tipo de Bean deberíamos usar todos y qué librería de importación? @HaritzPuerto

**Comment by HaritzPuerto** [comment]
la librería de Java EE 7 y los bean los habéis usado bien, si no, ya hubiéramos tenido problemas xDDD
Recordad usar RequestScoped siempre que sea posible!!!
