### ISSUE TITLE
tabla de expedientes demasiado ancha

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#37]
la tabla en la que se muestran los expedientes es demasiado ancha y me obliga a usar scrolling lateral. ¿Se podría ajustar el ancho automáticamente al ancho de la pantalla?

**Comment by steveomatic** [comment]
@HaritzPuerto  ya está hecho y mergeado con el master. El cambio era muy easy. Además he añadido una columna que es la de ciudadano_nombre, reemplazándola por ciudadano_id. (pienso que es más informativo así)

<a href="http://www.pic-upload.de/view-26866818/Captura5.png.html" target="_blank"><img src="http://www11.pic-upload.de/29.04.15/c5ii35xazjx2.png" alt="Bilder oder Fotos hochladen"></a>

<a href="http://www.pic-upload.de/view-26866823/Captura6.png.html" target="_blank"><img src="http://www11.pic-upload.de/29.04.15/yay3h7cbi78.png" alt="Bilder oder Fotos hochladen"></a>

**Comment by HaritzPuerto** [comment]
Toca usar bootstrap y googlear

**Comment by steveomatic** [comment]
Lo arreglaste en el último commit.
