### ISSUE TITLE
Cambios para la PROXIMA ENTREGA

### ISSUE THREAD

**Issue by steveomatic** [HaritzPuerto/SSCEntrega2#43]
- Añadir INGRESO en CIudadano
- Guardar Hash de las passwords.

**Comment by HaritzPuerto** [comment]
Ingreso ya está.
Está el campo hash ya implementado? @FelipeSulser

**Comment by FelipeSulser** [comment]
Se va a guardar como una String.
En el futuro, en una EJB se realizará una función hash, que transforma una String en su hash (en formato String).

Esta ya tó pensao.

**Comment by HaritzPuerto** [comment]
Eso ya está en el jpa,     
    @Column(nullable=false)
    private String contrasenia;

Es esto atributo no? @FelipeSulser

**Comment by FelipeSulser** [comment]
SIp
