### ISSUE TITLE
¿Por qué hay dos DAO de expediente?

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#47]
@FelipeSulser @steveomatic 
Un  dao permite comunicarnos con la DB. Si quiero comunicarme con expedientes, usaré un solo dao no?

**Comment by steveomatic** [comment]
MMM true, lo que pasa es que cada uno le ha puesto los métodos que necesita. Yo no veo problema en que esté así. Y si no, simplemente se añaden los métodos de uno al otro. @HaritzPuerto @FelipeSulser

**Comment by HaritzPuerto** [comment]
Puede haber un DAO por cada controlador
