### ISSUE TITLE
Añadir botón modificar cita al calendario

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#63]

**Comment by steveomatic** [comment]
Lo que puedo hacer es que cuando se clickee sobre una cita se pueda modificar la fecha, pero es horrible, piensa que eso tiene que cambiar también la  bd. Yo pienso que es mucho lío, y que mejor que cambien la cita a mano ¿no?

**Comment by HaritzPuerto** [comment]
ok
