### ISSUE TITLE
Creación vista agenda

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#8]
Al pinchar en un día, mostrar una lista con las citas de ese día en la misma vista. Esto está bien @fraanii94 ?

**Comment by fraanii94** [comment]
Correcto

**Comment by HaritzPuerto** [comment]
¿Cómo va eso @fraanii94 ?

**Comment by steveomatic** [comment]
Ya la he hecho yo. No daba tiempo si no. Mirad la PR

**Comment by HaritzPuerto** [comment]
Gracias @steveomatic está perfecta!
