### ISSUE TITLE
¿Qué requisitos ha cambiado cada uno?

### ISSUE THREAD

**Issue by AlvaroFaure** [HaritzPuerto/SSCEntrega2#80]
Si recordáis algo que haya cambiado, id listándolos aquí y ya yo los justifico.

@soutoner @FelipeSulser @steveomatic @fraanii94 @HaritzPuerto

**Comment by steveomatic** [comment]
-todas las paginas lleval al index si no estas logueado
-los expedientes se bucan por nombre, apellido1, apellido2 o num de expediente
-hay que tener foto de perfil ahora (añadir campo? que alguien lo mire @fraanii94 !!)
-en el perfil en el index se añaden querys de datos sobre el usuario (datos variados, estilo numero total de intervenciones)
-lo de las noticias tenemos que decir por qué 
-sé que se ha quitado algún botón por ahí pero no recuerdo cuál

**Comment by AlvaroFaure** [comment]
¿Lo de que hemos añadido noticias se considera un requisito? Claro que tenemos que explicarlo, pero no sé si en la zona de cambios en los requisitos. ¿Cómo lo ves? 

He añadido y explicado todos los requisitos en el documento y los que no tengo muy claro los he dejado en cursiva al final de esa sección. Consultadlo y aclaradme. Y seguid contándome por aquí.

**Comment by HaritzPuerto** [comment]
No creo que haya que ponerlo como un requisito ya que no lo es. Podríamos hacer un aparto de ampliaciones propuestas por nosotros.
