### ISSUE TITLE
Agenda de admin debe ir a todas citas

### ISSUE THREAD

**Issue by HaritzPuerto** [HaritzPuerto/SSCEntrega2#88]
Hay que corregir eso urgentemente. Es solo una línea, don't worry

**Comment by HaritzPuerto** [comment]
También hay que corregirlo en el diagrama @fraanii94

**Comment by fraanii94** [comment]
Corregido, en un momento lo subo a drive

**Comment by AlvaroFaure** [comment]
Te he dicho en el informe que: "El único matiz es que al administrador también se le lleva a lista_citas.xhtml si pincha en Agenda (además de si pincha en lista de citas)
Por lo demás creo que cumple todos los requisitos". No sé si lo has leído. Haritz coincide conmigo.

**Comment by steveomatic** [comment]
yo lo cambio en el xhtml
